version: '3.8'

services:
  backend:
    build: ./backend
    container_name: urlshortener-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: urlshortener-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: short_urls
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
